### ISSUE TITLE
Unable to run REPL in local machine

### ISSUE THREAD

**Issue by barreiros** [tidalcycles/strudel#132]
Hi! I'm trying to setup Strudel in my Windows local machine cloning Github repo but when I make "npm run repl" the process returns an error:

```
> @strudel.cycles/monorepo@0.0.1 repl
> cd repl && npm run dev


> @strudel.cycles/repl@0.0.0 dev
> vite


  vite v2.9.9 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 350ms.

X [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "WebDirt". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "WebDirt". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-59dc6e00.js:40662:10:
      40662 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40662:11)
    at resolvePackageEntry (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40658:9)
    at tryNodeResolve (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40465:20)
    at Context.resolveId (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40273:28)
    at Object.resolveId (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38837:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:39049:26)
    at async C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:39206:34
    at async callback (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:921:28)
    at async handleRequest (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:701:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-59dc6e00.js:39196:18:
      39196 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:39196:19)
    at handlePlugins (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:843:23)
    at Object.buildOrServe (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:1137:7)
    at C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:2079:17
    at new Promise (<anonymous>)
    at Object.build (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:2078:14)
    at Object.build (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:1927:51)
    at C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38997:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/App.jsx:15:25:
      15 │ import * as WebDirt from 'WebDirt';
         ╵                          ~~~~~~~~~

X [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "WebDirt". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "WebDirt". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-59dc6e00.js:40662:10:
      40662 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40662:11)
    at resolvePackageEntry (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40658:9)
    at tryNodeResolve (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40465:20)
    at Context.resolveId (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:40273:28)
    at Object.resolveId (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38837:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:39049:26)
    at async C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:39206:34
    at async callback (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:921:28)
    at async handleRequest (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:701:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-59dc6e00.js:39196:18:
      39196 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:39196:19)
    at handlePlugins (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:843:23)
    at Object.buildOrServe (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:1137:7)
    at C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:2079:17
    at new Promise (<anonymous>)
    at Object.build (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:2078:14)
    at Object.build (C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\esbuild\lib\main.js:1927:51)
    at C:\Users\Barreiros\Documents\Barreiros_Strudel\repl\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38997:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    ../packages/webdirt/webdirt.mjs:3:25:
      3 │ import * as WebDirt from 'WebDirt';
        ╵                          ~~~~~~~~~

Build failed with 2 errors:
node_modules/vite/dist/node/chunks/dep-59dc6e00.js:40662:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "WebDirt". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "WebDirt". The package may have incorrect main/module/exports specified in its package.json.
node_modules/vite/dist/node/chunks/dep-59dc6e00.js:40662:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "WebDirt". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "WebDirt". The package may have incorrect main/module/exports specified in its package.json.
```

Thanks!

**Comment by barreiros** [comment]
Maybe related with this update?

https://nodejs.org/api/deprecations.html#dep0128-modules-with-an-invalid-main-entry-and-an-indexjs-file

**Comment by felixroos** [comment]
Thanks for reporting, I just created this WebDirt issue: https://github.com/dktr0/WebDirt/issues/13 Until it‘s fixed, it might help to change the import path to WebDirt/js-src/WebDirt.js

**Comment by barreiros** [comment]
Ok. To solve I've made two changes in code ... 

** repl/App.jsx file, line 15
import * as WebDirt from '../../packages/webdirt/webdirt.mjs';

** packages/webdirt/webdirt.mjs file, line 4
import * as WebDirt from './js-src/webdirt.js';

...and I've taken the js-src folder directly from WebDirt repository because they was not in Strudel repository.

Thanks!

**Comment by felixroos** [comment]
I made the fix in WebDirt + updated the dependency in strudel, now it works on main see https://github.com/dktr0/WebDirt/pull/14
